name: CI test

on: push

env:
  TEST_DIR: ./packages/asar-differential-builder/test
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        name: install Node.js
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7.6.0
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: tsc build
        run: npm run build && npm run build:electron-updater

      - name: Install electron-update-example dependencies
        working-directory: ${{ format('{0}/electron-update-example', env.TEST_DIR) }}
        run: npm install

      - name: unit tests
        working-directory: ${{ env.TEST_DIR }}
        run: npm run test:unit

      - name: pre-generate electron projects
        working-directory: ${{ env.TEST_DIR }}
        run: echo 1 # npm run ci-generate-electron-projects

      - name: set DEBUG env
        run: echo "DEBUG=pw:browser" >> $GITHUB_ENV

      - name: e2e xvfb tests
        uses: GabrielBB/xvfb-action@v1
        with:
          working-directory: ${{ env.TEST_DIR }}
          run: npm run test:e2e
