name: CI test

on:
  push:
    branches: [ electron-asar-differential-updater ]

jobs:
  linux-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        name: checkout

      - uses: actions/setup-node@v3
        name: install Node.js
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7.6.0
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Install test/electron-update-example dependencies
        working-directory: test/electron-update-example
        run: npm install

      - name: tsc build
        run: npm run build

      - name: unit tests
        working-directory: ./test
        run: npm run test:unit

      - name: e2e xvfb tests
        uses: GabrielBB/xvfb-action@v1
        with:
          working-directory: ./test
          run: npm run test:e2e:gnu
